services:
  - type: web
    name: diwaanka-ajaanibka
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: OFFICER_USERNAME
        sync: false
      - key: OFFICER_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
